from __future__ import annotations

from src.career.models import JobRoleDefinition


JOB_ROLE_CATALOG: tuple[JobRoleDefinition, ...] = (
    JobRoleDefinition(
        role_id="cio",
        label="DSI / CIO",
        aliases=(
            "dsi",
            "directeur des systèmes d'information",
            "directrice des systèmes d'information",
            "chief information officer",
            "cio",
            "it director",
            "information systems director",
            "head of it",
            "group cio",
        ),
        core_skills=(
            "gouvernance si",
            "transformation si",
            "itil",
            "cobit",
            "cybersécurité",
            "architecture",
            "management",
        ),
        supporting_skills=(
            "agile",
            "pmp",
            "prince2",
            "cloud",
            "data",
            "sql",
            "azure",
        ),
        categories=(
            "technology",
            "executive",
            "management",
        ),
        preferred_providers=(
            "FranceTravail",
            "APEC",
            "WelcomeToTheJungle",
            "LinkedIn",
        ),
    ),
    JobRoleDefinition(
        role_id="cto",
        label="CTO / Directeur technique",
        aliases=(
            "cto",
            "chief technology officer",
            "directeur technique",
            "directrice technique",
            "technology director",
            "vp engineering",
            "vice president engineering",
            "head of engineering",
            "engineering director",
        ),
        core_skills=(
            "architecture",
            "cloud",
            "software engineering",
            "management",
            "delivery",
        ),
        supporting_skills=(
            "python",
            "sql",
            "azure",
            "aws",
            "gcp",
            "docker",
            "kubernetes",
            "agile",
            "scrum",
            "generative ai",
        ),
        categories=(
            "technology",
            "executive",
            "engineering",
        ),
        preferred_providers=(
            "RemoteOK",
            "APEC",
            "WelcomeToTheJungle",
            "LinkedIn",
        ),
    ),
    JobRoleDefinition(
        role_id="it_program_director",
        label="Directeur de programme IT",
        aliases=(
            "directeur de programme",
            "directrice de programme",
            "directeur de programme it",
            "program director",
            "programme director",
            "program manager",
            "programme manager",
            "it program manager",
            "transformation program director",
        ),
        core_skills=(
            "gestion de programme",
            "gestion de projet",
            "pmp",
            "prince2",
            "gouvernance si",
        ),
        supporting_skills=(
            "agile",
            "scrum",
            "transformation si",
            "cobit",
            "itil",
            "management",
            "budget",
            "risques",
        ),
        categories=(
            "technology",
            "program_management",
            "management",
        ),
        preferred_providers=(
            "FranceTravail",
            "APEC",
            "WelcomeToTheJungle",
            "LinkedIn",
        ),
    ),
    JobRoleDefinition(
        role_id="it_project_director",
        label="Directeur de projet IT",
        aliases=(
            "directeur de projet",
            "directrice de projet",
            "directeur de projet it",
            "it project director",
            "senior project manager",
            "project director",
            "delivery director",
            "delivery manager",
        ),
        core_skills=(
            "gestion de projet",
            "pmp",
            "prince2",
            "agile",
        ),
        supporting_skills=(
            "scrum",
            "transformation si",
            "gouvernance si",
            "budget",
            "risques",
            "management",
        ),
        categories=(
            "technology",
            "project_management",
            "management",
        ),
        preferred_providers=(
            "FranceTravail",
            "APEC",
            "WelcomeToTheJungle",
            "LinkedIn",
            "RemoteOK",
        ),
    ),
    JobRoleDefinition(
        role_id="pmo_director",
        label="Directeur PMO",
        aliases=(
            "directeur pmo",
            "directrice pmo",
            "pmo director",
            "head of pmo",
            "responsable pmo",
            "portfolio management officer",
            "portfolio director",
        ),
        core_skills=(
            "gestion de programme",
            "gestion de projet",
            "gouvernance si",
            "pmp",
        ),
        supporting_skills=(
            "prince2",
            "agile",
            "cobit",
            "budget",
            "risques",
            "reporting",
        ),
        categories=(
            "program_management",
            "governance",
            "management",
        ),
        preferred_providers=(
            "FranceTravail",
            "APEC",
            "WelcomeToTheJungle",
            "LinkedIn",
        ),
    ),
    JobRoleDefinition(
        role_id="transformation_director",
        label="Directeur de la transformation",
        aliases=(
            "directeur de la transformation",
            "directrice de la transformation",
            "transformation director",
            "digital transformation director",
            "it transformation director",
            "head of transformation",
            "transformation manager",
            "change director",
        ),
        core_skills=(
            "transformation si",
            "gouvernance si",
            "gestion de programme",
            "management",
        ),
        supporting_skills=(
            "agile",
            "scrum",
            "pmp",
            "prince2",
            "cobit",
            "itil",
            "cloud",
            "data",
        ),
        categories=(
            "transformation",
            "management",
            "technology",
        ),
        preferred_providers=(
            "FranceTravail",
            "APEC",
            "WelcomeToTheJungle",
            "LinkedIn",
        ),
    ),
    JobRoleDefinition(
        role_id="data_engineer",
        label="Data Engineer",
        aliases=(
            "data engineer",
            "ingénieur data",
            "ingénieure data",
            "data platform engineer",
            "cloud data engineer",
            "analytics engineer",
        ),
        core_skills=(
            "python",
            "sql",
            "etl",
        ),
        supporting_skills=(
            "spark",
            "azure",
            "aws",
            "gcp",
            "databricks",
            "airflow",
            "docker",
            "kubernetes",
        ),
        categories=(
            "technology",
            "data",
            "engineering",
        ),
        preferred_providers=(
            "RemoteOK",
            "FranceTravail",
            "APEC",
            "WelcomeToTheJungle",
        ),
    ),
    JobRoleDefinition(
        role_id="cloud_architect",
        label="Cloud Architect",
        aliases=(
            "cloud architect",
            "architecte cloud",
            "cloud solution architect",
            "solution architect",
            "solutions architect",
            "enterprise cloud architect",
        ),
        core_skills=(
            "architecture",
            "cloud",
        ),
        supporting_skills=(
            "azure",
            "aws",
            "gcp",
            "docker",
            "kubernetes",
            "terraform",
            "devops",
            "cybersécurité",
        ),
        categories=(
            "technology",
            "cloud",
            "architecture",
        ),
        preferred_providers=(
            "RemoteOK",
            "FranceTravail",
            "APEC",
            "WelcomeToTheJungle",
        ),
    ),
    JobRoleDefinition(
        role_id="cfo",
        label="DAF / CFO",
        aliases=(
            "daf",
            "directeur administratif et financier",
            "directrice administrative et financière",
            "chief financial officer",
            "cfo",
            "finance director",
            "financial director",
            "head of finance",
        ),
        core_skills=(
            "finance",
            "contrôle de gestion",
            "trésorerie",
            "consolidation",
            "budget",
        ),
        supporting_skills=(
            "audit",
            "fiscalité",
            "erp",
            "reporting",
            "management",
            "risques",
        ),
        categories=(
            "finance",
            "executive",
            "management",
        ),
        preferred_providers=(
            "FranceTravail",
            "APEC",
            "WelcomeToTheJungle",
            "LinkedIn",
        ),
    ),
)